### ISSUE TITLE
When 2 or more actions have the same priority, just one registered

### ISSUE THREAD

**Issue by midoalone** [tormjens/eventy#1]
When I tried to register more than one action with the same priority, just on of them "The last one" is registered and override the others.

**Comment by tormjens** [comment]
Sorry for the late response. I'll have a look at it ASAP!

**Comment by wpcodingca** [comment]
Was this ever fixed?

**Comment by rashcms** [comment]
unfortunately this bug has not beed fixed yet

**Comment by rashcms** [comment]
I have fixed this issue with some tricks by changing listen function
file Event.php
`public function listen($hook, $callback, $priority = 20, $arguments = 1)
	{
		$i = 0;
		$uniquePriority = $priority;
		do
		{
			if( isset( $this->listeners[$uniquePriority][$hook] ) )
			{
				$i += 0.1;
				$uniquePriority = $priority + $i;
			}	
		} while( isset( $this->listeners[$uniquePriority][$hook] ) );
		$this->listeners[$uniquePriority][$hook] = compact('callback', 'arguments');
	}`

**Comment by tormjens** [comment]
Great stuff! Thanks.
