### ISSUE TITLE
this package not work in laravel 5.7

### ISSUE THREAD

**Issue by masami6871** [tormjens/eventy#15]
Hi   .  
i installed  this package on my project  .  i used  laravel  5.7 . 
first  i didn`t set facade  and  providers  in  app.php and  i tryed to use from Eventy facade.
but didn`t work . 

![1](https://user-images.githubusercontent.com/29583593/52563707-6f6c3a00-2e17-11e9-8940-785d0383a24b.jpg)

then   i set  facade  and  providers  in  app.php but  didn`t work again . 

![2](https://user-images.githubusercontent.com/29583593/52563867-cbcf5980-2e17-11e9-9999-7756ce4697ae.jpg)

or  

![3](https://user-images.githubusercontent.com/29583593/52563894-dc7fcf80-2e17-11e9-940b-148097e1fdf5.jpg)

![4](https://user-images.githubusercontent.com/29583593/52563919-ec97af00-2e17-11e9-8bd8-9c03a04e43e1.jpg)

then  when  i  used  Eventy::action i see  this  error  :  

![5](https://user-images.githubusercontent.com/29583593/52564062-5b750800-2e18-11e9-9d36-a23fc6ab362c.jpg)

please  help me  .  
thanks

**Comment by tormjens** [comment]
Hey,

This is not an error with Eventy and your error message is pretty clear: `App\Http\Controllers\Admin\Eventy` does not exist.

The facade is registered automatically when you install the package (if you have auto-discovery turned on), but that registers the facade to the global namespace. To access the global namespace from any classes you'd need to prefix the class name with a `\`. So the call would be `\Eventy::addAction(...)`.

However, I prefer to import/use/declare my facades when I'm using them in a class context. You can do this two ways.

1. Using the globally registered facade: `use Eventy;`
2. Using the fully qualified namespace directly: `use TorMorten\Eventy\Facades\Events as Eventy;`

I'd recommend the second option as it gives you better IDE support and is more clear where the code comes from.

So to conclude:, a controller that would use `Eventy` would look somewhat like this:

```php 
namespace App\Http\Controllers;

use Illuminate\Routing\Controller;
use TorMorten\Eventy\Facades\Events as Eventy;

class FooController extends Controller
{
    public function index() 
    {
        ...
        Eventy::action('my.hook');
        ...
    }
}
```
