### ISSUE TITLE
How to remove a Anonymous callable action

### ISSUE THREAD

**Issue by zotopteam** [tormjens/eventy#16]
When i add a action:
`Eventy::addAction('foo', function() {
     echo 'bar';
});`

Then I want to remove it, How to do this?

`Eventy::remove('foo', ……);`

**Comment by tormjens** [comment]
Good question. The function is anonymous so you wouldn't have a reference to it to remove it later on.

I'll try and come up with a solution for your issue. I'll get back to you!

**Comment by tormjens** [comment]
@zotopteam I've implemented functionality for this with #17. Mind giving it a go?

**Comment by zotopteam** [comment]
Thanks，  #17 is pretty！
