### ISSUE TITLE
Too few arguments error

### ISSUE THREAD

**Issue by freescout-helpdesk** [tormjens/eventy#19]
If one of the parameters passed to `\Eventy::filter()` (or 'action()') is `null` you will get "Too few arguments..." error:

```
    \Eventy::addFilter('filter_name', function($test1, $test2) {
        return $test1;
    }, 20, 2);

    $test1 = 1;
    $tes2 = null;
    \Eventy::filter('filter_name', $test1, $test2);
```

**Comment by tormjens** [comment]
@freescout-helpdesk Sorry for the late response. I'll look into this. Thanks for reporting.

**Comment by tormjens** [comment]
Fixed in 0.5.6 :)

**Comment by freescout-helpdesk** [comment]
Same issue with actions (Action.php)

**Comment by tormjens** [comment]
@freescout-helpdesk Should be fixed in the latest release. If you have any further issues, please open a new issue.
