### ISSUE TITLE
Does this support queue

### ISSUE THREAD

**Issue by tekkenking** [tormjens/eventy#22]
First of all, thank you so very much for this wonderful package..

What i would like to know now is, does this packages support queue?

Secondly it seems most of my application logic would reside in service-provider or is there something I'm not getting.

I await your  humble clearance,

Thanks in advance

**Comment by tormjens** [comment]
No, this does not support queue. If you need to run something in the background you have to run a job in a trafitional Laravel manner.

The meaning behind this package is not to put all your application logic in the service provider. It is about allowing your application to be extended from other pieces of code.

For example; in my application I put all my code in separate composer packages. All those have a service provider of their own. This way package B can extend the functionality of package B.

I can give you some more concrete examples of how I use this in my app if you’d like?

**Comment by tormjens** [comment]
Actually I outlined it pretty well in #20
