### ISSUE TITLE
Package jeremeamia/superclosure is abandoned.

### ISSUE THREAD

**Issue by hoseinrafiei** [tormjens/eventy#26]
Hi,

After installing by composer I receive this error.

> Package jeremeamia/superclosure is abandoned, you should avoid using it. Use opis/closure instead.

**Comment by tormjens** [comment]
Hi @hoseinrafiei 

Thanks for reporting. I'll update and create a new release within the week :)

**Comment by tormjens** [comment]
Swapped in the 0.6 release.
