### ISSUE TITLE
Accepting array callables

### ISSUE THREAD

**Issue by mrchimp** [tormjens/eventy#3]
First off, good work on the package! It's one of the better bits of Wordpress and you've made it really easy to use.

I do have a small issue though. Currently I can pass a closure:

    Eventy::addAction('foo', function() {
         echo 'bar';
    });

...or a string

    Eventy::addAction('foo', 'someClass@baz');

...but I can't pass a callable array:

    Eventy::addAction('foo', [$this, 'bar']);

This would be really helpful as it would allow me to access the current scope of `$this` which processing the action.

This could be achieved by updating the `Event` `getFunction` method to the following:

    protected function getFunction($callback)
    {
        if (is_string($callback) && strpos($callback, '@')) {
            $callback = explode('@', $callback);
            return array(app('\\' . $callback[0]), $callback[1]);
        } else if (is_callable($callback)) {
            return $callback;
        } else {
            throw new Exception('$callback is not a Callable', 1);
        }
    }

If this looks good to you I can submit a pull request.

Cheers!

**Comment by tormjens** [comment]
That looks great. I'll be happy to accept a PR ;)

**Comment by tormjens** [comment]
Fixed via #4

**Comment by mrchimp** [comment]
Thanks for merging that. Could you publish it to packagist.org when you get a chance?

Cheers!

**Comment by tormjens** [comment]
Sure! Tagged 0.3 in Packagist now :)

**Comment by mrchimp** [comment]
Awesome! I just found your answer here, too https://github.com/JeffreyWay/laravel-elixir-vueify/issues/24

You're helping me out a lot today!

**Comment by tormjens** [comment]
I'm on fire today! Glad to help, and again, thanks for the PR ;)
