### ISSUE TITLE
Alternative to use outside laravel 

### ISSUE THREAD

**Issue by Stevemoretz** [tormjens/eventy#30]
Hi I use vanilla php sometimes is there any way to get this working without laravel, or do you know any other alternative?

**Comment by Stevemoretz** [comment]
> Hey! Someone forked the package in #14 so you might try that ;)

Hi, thank you so much for the quick answer that fork is a little bit old, you mentioned it is possible to use it on that issue though, would you mind provide an example I rather use the main library rather than that fork.

**Comment by tormjens** [comment]
The very minimum is that your app uses composer. While my package doesnt directly require the Laravel framework it has a couple of dependencies which will be cumbersome til include manually.

if your app uses Composer the test suite serves as a good example on how to use it outside of Laravel.

https://github.com/tormjens/eventy/blob/master/tests/Unit/ActionTest.php

**Comment by Stevemoretz** [comment]
> The very minimum is that your app uses composer. While my package doesnt directly require the Laravel framework it has a couple of dependencies which will be cumbersome til include manually.
> 
> if your app uses Composer the test suite serves as a good example on how to use it outside of Laravel.
> 
> https://github.com/tormjens/eventy/blob/master/tests/Unit/ActionTest.php

Yes of course what doesn't use composer thank you so much!
