### ISSUE TITLE
Laravel 10 issue

### ISSUE THREAD

**Issue by hamedkhorasani** [tormjens/eventy#46]
The package is very good. I tested it in Laravel 10 but it gives following error.
"A facade root has not been set."
Will the package be updated for this version?

**Comment by tormjens** [comment]
@hamedkhorasani I have not upgraded my apps to L10 yet, so have not had the need to upgrade this package yet. Will check :)

**Comment by hamedkhorasani** [comment]
I'm looking forward to seeing when you will check :)

**Comment by tormjens** [comment]
I've now upgraded my stuff, buiti I don't see this error.

Could you provide a stack trace?
