### ISSUE TITLE
At least 30% speed improvement

### ISSUE THREAD

**Issue by freescout-helpdesk** [tormjens/eventy#56]
See https://github.com/freescout-helpdesk/freescout/pull/3263

**Comment by tormjens** [comment]
@freescout-helpdesk Thanks. Will check :)

**Comment by tormjens** [comment]
@freescout-helpdesk This has been resolved with commit 8b86cb2351b061f4f6562f9dbccc525597c8271e and b5327c71def04352ef1febf4797cef860f7e3789

It is now tagged in https://github.com/tormjens/eventy/releases/tag/0.9.3
