### ISSUE TITLE
Decrease the 5.5 requirement to 5.3

### ISSUE THREAD

**Issue by mattallan** [tormjens/eventy#6]
Hey, firstly very awesome package!

I've got a project that is running the Lumen v5.3 and I'm currently having to manually include the eventy package files into my project because of the 5.5 `illuminate/support` requirement.

I'm curious if you see any issues with decreasing the requirement from 5.5 as it appears to work fine on 5.3 (i could be missing something)

I would be happy to push up a patch to reduce the requirement to 5.3, if you okay with it, I can also push up some notes on installation for Lumen (different steps required to the ones in your readme)

**Comment by mattallan** [comment]
I just found this: https://github.com/gavande/eventy/tree/master

It's your files but only requires 5.3.

**Comment by tormjens** [comment]
Hi @mattallan. Thanks for your kind words. Appreciate it!

I see no issues with decreasing the requirement. Was merely put there as the current iteration is only tested with 5.5. I've added a patch for this now.

**Comment by tormjens** [comment]
Also, if you'd push up some notes about using it in Lumen I would really appreciate it :)
