### ISSUE TITLE
Release 0.5.2 to Packagist

### ISSUE THREAD

**Issue by gRoberts84** [tormjens/eventy#7]
Hey there,

I've just installed via composer and it's pulling down 0.5.1, which doesn't include EventBladeServiceProvider.php.

Could you possibly push 0.5.2 to Packagist so we can pull from composer 😄 

Cheers

**Comment by tormjens** [comment]
Weird that Packagist wasn’t able to pick up on it. I’ve pushed a new relrase now (0.5.3).

Thanks for letting me know :)

**Comment by gRoberts84** [comment]
Thanks and great work! 😉
