### ISSUE TITLE
use Eventy in other system, other than Lavarel

### ISSUE THREAD

**Issue by danaoairuike** [tormjens/eventy#78]
Hello, sir,

Thank you for this package.  It's really great. So, I'm trying to explore the possibility that whether I can use it in my project. It's a CMS, and without Laravel, or composer. 

I think the core of Eventy is mature enough so that it _can_  be independent from Laravel.  I think the core of Eventy does not need the two provider classes, or the Facades directory, does it ? since they are Laravel-specific. If I don't use it in Laravel, I don't need them. Is it possible?

![image](https://github.com/tormjens/eventy/assets/129480823/a3f15e93-815f-4d9f-bbcc-1ad50e9bbe15)

And in the `HashedCallable` class, can we use other way to replace the Laravel `SerializableClosure`? I mean, with a simple way, not using another package. But if we really have to use Laravel `SerializableClosure`, I think it's okay, since the package Laravel [serializable-closure](https://github.com/laravel/serializable-closure) has zero dependency.  I just add it to the vendor along with your excellent Eventy. But I really hope we can replace it with another simpler way to serialize callbacks.

![image](https://github.com/tormjens/eventy/assets/129480823/26c28cd4-7496-46f7-8121-6fd8392df195)

Could you help me answer these  questions? Thank you.

**Comment by tormjens** [comment]
@danaoairuike There's a fork of the package which doesnt have any dependencies and should work all the way down to PHP 5.4. See https://github.com/filips123/eventy/
